#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
# yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          off
# yabai -m config window_placement             second_child
# yabai -m config window_topmost               on
# yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config window_shadow                on
# yabai -m config insert_feedback_color        0xaad75f5f
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90
# yabai -m config split_ratio                  0.50
# yabai -m config auto_balance                 off
# yabai -m config mouse_modifier               alt+ctrl+cmd
# yabai -m config mouse_action1                move
# yabai -m config mouse_action2                resize
# yabai -m config window_topmost               on


# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  1
yabai -m config bottom_padding               1
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   6
yabai -m config external_bar all:0:26

yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^Cisco Secure Client$" manage=off
yabai -m rule --add app="^Cisco Secure Client$" manage=off
yabai -m rule --add app="^zoom.us$" manage=on

yabai -m signal --add event=display_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-jsx\"'"

# https://github.com/koekeishiya/yabai/issues/535
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"nibar-spaces-jsx\"'"
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"nibar-bar-jsx\"'"
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"nibar-status-jsx\"'"

yabai -m signal --add event=window_focused action="~/.yabai/notify_bar_status.sh"

echo "yabai configuration loaded.."
